website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

PROJECT_ROOT = path.dirname(path.realpath(__file__))
DATABASE = path.join(PROJECT_ROOT, 'database.db')


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DATABASE}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists(DATABASE):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Note
from . import db
import json

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if current_user.is_authenticated:
        return render_template("home.html", user=current_user)   

    return redirect(url_for('auth.login'))


@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/light/loader.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/dark/loader.css') }}" rel="stylesheet" type="text/css" />
    <script src="{{ url_for('static', filename = 'layouts/modern-light-menu/loader.js') }}"></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="{{ url_for('static', filename = 'src/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    
    
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/light/plugins.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/light/authentication/auth-boxed.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/dark/plugins.css') }}" rel="stylesheet" type="text/css" />

    <link href="{{ url_for('static', filename = 'src/plugins/src/apex/apexcharts.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/light/dashboard/dash_1.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/dark/dashboard/dash_1.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/light/scrollspyNav.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/plugins/css/light/apex/custom-apexcharts.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/dark/scrollspyNav.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/plugins/css/dark/apex/custom-apexcharts.css') }}" rel="stylesheet" type="text/css" />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body class="layout-boxed">
    <!-- BEGIN LOADER -->
    <div id="load_screen"> <div class="loader"> <div class="loader-content">
      <div class="spinner-grow align-self-center"></div>
  </div></div></div>
  <!--  END LOADER -->

  <!--  BEGIN NAVBAR  -->
  <div class="header-container container-xxl">
      <header class="header navbar navbar-expand-sm expand-header">

          <a href="javascript:void(0);" class="sidebarCollapse">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
          </a>

          <div class="search-animated toggle-search">
            
          </div>

          <ul class="navbar-item flex-row ms-lg-auto ms-0">

              <li class="nav-item dropdown user-profile-dropdown  order-lg-0 order-1">
                  <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <div class="avatar-container">
                          <div class="avatar avatar-sm avatar-indicators avatar-online">
                              <img alt="avatar" src="{{ url_for('static', filename = 'src/assets/img/profile-30.png') }}" class="rounded-circle">
                          </div>
                      </div>
                  </a>

                  <div class="dropdown-menu position-absolute" aria-labelledby="userProfileDropdown">
                      <div class="dropdown-item">
                          <a href="{{ url_for('auth.logout') }}">
                              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg> <span>Log Out</span>
                          </a>
                      </div>
                  </div>
                  
              </li>
          </ul>
      </header>
  </div>
  <!--  END NAVBAR  -->

   <!--  BEGIN MAIN CONTAINER  -->
   <div class="main-container" id="container">

    <div class="overlay"></div>
    <div class="search-overlay"></div>

    <!--  BEGIN SIDEBAR  -->
    <div class="sidebar-wrapper sidebar-theme">

        <nav id="sidebar">

            <div class="navbar-nav theme-brand flex-row  text-center">
                <div style="display: none;" class="nav-logo">
                    <div class="nav-item theme-logo">
                        <a href="./index.html">
                            <img src="#" class="navbar-logo" alt="logo">
                        </a>
                    </div>
                    <div class="nav-item theme-text">
                        <a href="./index.html" class="nav-link"> CORK </a>
                    </div>
                </div>
                <div style="display: none;" class="nav-item sidebar-toggle">
                    <div class="btn-toggle sidebarCollapse">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg>
                    </div>
                </div>
            </div>

            <div style="display: none;" class="profile-info">
                <div class="user-info">
                    <div class="profile-img">
                        <img src="{{ url_for('static', filename = 'src/assets/img/profile-30.png') }}" alt="avatar">
                    </div>
                    <div class="profile-content">
                        <h6 class="">Shaun Park</h6>
                        <p class="">Project Leader</p>
                    </div>
                </div>
            </div>
                            
            <div class="shadow-bottom"></div>
            <ul class="list-unstyled menu-categories" id="accordionExample">
                <li class="menu active">
                    <a href="#dashboard" data-bs-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                        <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            <span>Dashboard</span>
                        </div>
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                        </div>
                    </a>
                    <ul class="collapse submenu list-unstyled show" id="dashboard" data-bs-parent="#accordionExample">
                        <li class="active">
                            <a href="#"> Analytics </a>
                        </li>
                    </ul>
                </li>
                
            </ul>
            
        </nav>

    </div>
    <!--  END SIDEBAR  -->

    <!--  BEGIN CONTENT AREA  -->
    <div id="content" class="main-content">
      {% block content %} {% endblock %}
        <!--  BEGIN FOOTER  -->
        <div class="footer-wrapper">
            <div class="footer-section f-section-1">
                <p class="">Copyright © <span class="dynamic-year">2022</span> <a target="_blank" href="https://designreset.com/cork-admin/">DesignReset</a>, All rights reserved.</p>
            </div>
            <div class="footer-section f-section-2">
                <p class="">Coded with <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg></p>
            </div>
        </div>
        <!--  END FOOTER  -->
    </div>
    <!--  END CONTENT AREA  -->

</div>
<!-- END MAIN CONTAINER -->
    

    <script src="{{ url_for('static', filename = 'src/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/mousetrap/mousetrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/waves/waves.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'layouts/modern-light-menu/app.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/highlight/highlight.pack.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/apex/apexcharts.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/assets/js/dashboard/dash_1.js') }}"></script>

    <script src="{{ url_for('static', filename = 'src/plugins/src/apex/apexcharts.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/apex/custom-apexcharts.js') }}"></script>

  </body>
</html>

website/templates/base_auth.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/light/loader.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/dark/loader.css') }}" rel="stylesheet" type="text/css" />
    <script src="{{ url_for('static', filename = 'layouts/modern-light-menu/loader.js') }}"></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="{{ url_for('static', filename = 'src/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    
    
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/light/plugins.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/light/authentication/auth-boxed.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'layouts/modern-light-menu/css/dark/plugins.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/dark/authentication/auth-boxed.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename = 'src/assets/css/light/elements/alert.css') }}" rel="stylesheet" type="text/css" />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body class="form">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <!-- <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> -->
      <div class="alert alert-light-danger alert-dismissible fade show border-0 mb-4" role="alert"> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> 
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x close" data-bs-dismiss="alert"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button> 
        <strong>Error!</strong> {{ message }}
      </div>

      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}

    {% block content %} {% endblock %}
    <!-- <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script> -->
    <script src="{{ url_for('static', filename = 'src/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/mousetrap/mousetrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/waves/waves.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'layouts/modern-light-menu/app.js') }}"></script>
    <script src="{{ url_for('static', filename = 'src/plugins/src/highlight/highlight.pack.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename = 'src/assets/js/scrollspyNav.js') }}"></script> -->


  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="layout-px-spacing">

  <h2>Name: Nguyen Duc Anh</h2>
  <h2>ID: 2021712226</h2>

  <div class="middle-content container-xxl p-0">

      <div class="row layout-top-spacing">

          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
              <div class="widget widget-chart-three">
                <div class="widget-heading">
                  <h5 class="value">Graphic design</h5>
                </div>
                  <div class="widget-content">
                    <img src="{{ url_for('static', filename = 'src/assets/img/chart-1.jpg') }}">

                  </div>
              </div>
              
          </div>

          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
            <div class="widget widget-chart-three">
              <div class="widget-heading">
                <h5 class="value">Population affected by aqueous arsenic </h5>
              </div>
                <div class="widget-content">
                  <div id="donut-chart" class=""></div>
                </div>
            </div>
          </div> 
          
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
            <div class="widget widget-chart-three">
              <div class="widget-heading">
                <h5 class="value">Final nutrient against time (day) </h5>
              </div>
                <div class="widget-content">
                  <div id="column-chart" class=""></div>
                </div>
            </div>
          </div> 

          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
            <div class="widget widget-chart-three">
              <div class="widget-heading">
                <h5 class="value">Toxicity of aqueous arsenic species </h5>
              </div>
                <div class="widget-content">
                  <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">As species</th>
                                <th scope="col">LD50 (g/kg)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Arsine</td>
                                <td>0.003</td>
                            </tr>
                            <tr>
                              <td>Arsenite</td>
                              <td>0.014</td>
                            </tr>
                            <tr>
                              <td>Arsenate</td>
                              <td>0.02</td>
                            </tr>
                            <tr>
                              <td>(Di,Tri)-methyl arsine </td>
                              <td>7.87</td>
                            </tr>
                            <tr>
                              <td>Methylarsonic acid</td>
                              <td>0.7-1.8</td>
                            </tr>
                            <tr>
                              <td>Dimethylarsinic acid</td>
                              <td>0.7-2.6</td>
                            </tr>
                            <tr>
                              <td>Trimethylarsine oxide</td>
                              <td>10</td>
                            </tr>
                            <tr>
                              <td>Tetramethylarsonium ion</td>
                              <td>0.89</td>
                            </tr>
                            <tr>
                              <td>Arsenocholine</td>
                              <td>10</td>
                            </tr>
                            <tr>
                              <td>Arsenobetaine</td>
                              <td>10</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                </div>
            </div>
          </div> 

          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 layout-spacing">
            <div class="widget widget-chart-three">
              <div class="widget-heading">
                <h5 class="value">Water volume against time</h5>
              </div>
                <div class="widget-content">
                  <div id="line-chart-timeseries" class=""></div>
                </div>
            </div>
          </div> 

      </div>

  </div>

</div>
{% endblock %}

website/templates/login.html
{% extends "base_auth.html" %} {% block title %}Login{% endblock %} {% block content
%}
<!-- BEGIN LOADER -->
<div id="load_screen"> <div class="loader"> <div class="loader-content">
  <div class="spinner-grow align-self-center"></div>
</div></div></div>
<!--  END LOADER -->

<div class="auth-container d-flex">

  <div class="container mx-auto align-self-center">

      <div class="row">

          <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-8 col-12 d-flex flex-column align-self-center mx-auto">
              <div class="card mt-3 mb-3">
                  <div class="card-body">
                    <form method="POST">
                      <div class="row">
                          <div class="col-md-12 mb-3">
                              
                              <h2>Sign In</h2>
                              <p>Enter your email and password to login</p>
                              
                          </div>
                          <div class="col-md-12">
                              <div class="mb-3">
                                  <label class="form-label">Email</label>
                                  <input  id="email" name="email" type="email" class="form-control">
                              </div>
                          </div>
                          <div class="col-12">
                              <div class="mb-4">
                                  <label class="form-label">Password</label>
                                  <input id="password" name="password" type="password" class="form-control">
                              </div>
                          </div>
                          
                          <div class="col-12">
                              <div class="mb-4">
                                  <button type="submit" class="btn btn-secondary w-100">SIGN IN</button>
                              </div>
                          </div>

                          <div class="col-12">
                              <div class="text-center">
                                  <p class="mb-0">Dont't have an account ? <a href="{{ url_for('auth.sign_up') }}" class="text-warning">Sign Up</a></p>
                              </div>
                          </div>
                          
                      </div>
                    </form>
                  </div>
              </div>
          </div>
          
      </div>
      
  </div>

</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base_auth.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}

 <!-- BEGIN LOADER -->
<div id="load_screen"> <div class="loader"> <div class="loader-content">
  <div class="spinner-grow align-self-center"></div>
</div></div></div>
<!--  END LOADER -->

<div class="auth-container d-flex">

  <div class="container mx-auto align-self-center">
    <form method="POST">
      <div class="row">

          <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-8 col-12 d-flex flex-column align-self-center mx-auto">
              <div class="card mt-3 mb-3">
                  <div class="card-body">
                    <form method="POST">
                      <div class="row">
                          <div class="col-md-12 mb-3">
                              
                              <h2>Sign Up</h2>
                              <p>Enter your email and password to register</p>
                              
                          </div>
                          <div class="col-md-12">
                              <div class="mb-3">
                                  <label class="form-label">Name</label>
                                  <input id="firstName" name="firstName" type="text" class="form-control add-billing-address-input">
                              </div>
                          </div>
                          <div class="col-md-12">
                              <div class="mb-3">
                                  <label class="form-label">Email</label>
                                  <input  id="email" name="email" type="email" class="form-control">
                              </div>
                          </div>
                          <div class="col-12">
                              <div class="mb-3">
                                  <label class="form-label">Password</label>
                                  <input id="password1" name="password1" type="text" class="form-control">
                              </div>
                          </div>

                          <div class="col-12">
                            <div class="mb-3">
                                <label class="form-label">Confirm Password</label>
                                <input id="password2" name="password2" type="text" class="form-control">
                            </div>
                        </div>
                          
                          <div class="col-12">
                              <div class="mb-4">
                                  <button type="submit" class="btn btn-secondary w-100">SIGN UP</button>
                              </div>
                          </div>               

                          <div class="col-12">
                              <div class="text-center">
                                  <p class="mb-0">Already have an account ? <a href="{{ url_for('auth.login') }}" class="text-warning">Sign in</a></p>
                              </div>
                          </div>
                          
                      </div>
                    </form> 
                  </div>
              </div>
          </div>
          
      </div>
      
  </div>

</div>
{% endblock %}